(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const css=n=>getComputedStyle(document.body).getPropertyValue(n).trim();
const id=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const colors=['#5865D9','#2CA878','#F59E0B','#DC5353','#8B5CF6','#06A6C7','#DB5DA0','#7AA52D'];
const color=()=>colors[Math.floor(Math.random()*colors.length)];
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)};
const open=id=>$('#'+id).classList.add('show'), close=id=>$('#'+id).classList.remove('show');
const KEY='dataview_repository_v1';
const state={repos:load(),current:null,type:'bar',hidden:new Set(),chart:null,compare:null,deleteId:null};
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.repos))}
const repo=()=>state.repos.find(r=>r.id===state.current)||null;
const select=id=>{state.current=id;state.hidden.clear()};
const meta={home:['Início','Comece criando seu primeiro repositório.'],repos:['Repositórios','Crie e organize os conjuntos de informações do projeto.'],compare:['Comparações','Coloque dois conjuntos de dados lado a lado.'],editor:['Editor','Adicione ou altere as informações do repositório.'],chart:['Gráficos','Escolha o formato que melhor explica seus dados.']};
function go(route){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+route)?.classList.add('active');$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.route===route));const m=meta[route]||meta.home;$('#topTitle').textContent=m[0];$('#topSubtitle').textContent=m[1]}
const steps=[['Bem-vindo ao DataView','Este sistema organiza informações e transforma os dados em gráficos fáceis de explicar.'],['Crie um repositório','Pense nele como uma pasta: “Entregas”, “Pesquisa”, “Atendimentos”. É onde seus dados ficam agrupados.'],['Cadastre os dados','Cada linha recebe um nome, um valor e uma cor. Você pode mudar essas informações quando quiser.'],['Apresente os resultados','Escolha barras, linha, pizza, rosca, radar, polar ou 3D. Depois use Comparações para colocar dois conjuntos lado a lado.']];let step=0;
function tutorial(){const [title,text]=steps[step];$('#tutorialStep').textContent=`${step+1} de ${steps.length}`;$('#tutorialTitle').textContent=title;$('#tutorialText').textContent=text;$$('#tutorialProgress span').forEach((d,i)=>d.classList.toggle('active',i===step));$('#startWelcome').textContent=step===steps.length-1?'Começar':'Continuar'}
function finishTutorial(){close('welcome');localStorage.setItem('dataview_tutorial_seen','1')}
function card(r){const c=document.createElement('article');c.className='repo-card';c.style.setProperty('--accent',r.data[0]?.color||'#5865D9');c.innerHTML=`<div class="repo-card-top"><div class="folder">📁</div><button class="repo-delete">×</button></div><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><div class="repo-card-meta"><span>${r.data.length} ${r.data.length===1?'categoria':'categorias'}</span><span>${r.data.length?'Ver gráfico →':'Adicionar dados →'}</span></div>`;c.onclick=e=>{if(e.target.closest('.repo-delete'))return;select(r.id);r.data.length?openChart():(renderEditor(),go('editor'))};c.querySelector('.repo-delete').onclick=e=>{e.stopPropagation();state.deleteId=r.id;open('deleteModal')};return c}
function renderRepos(){const h=$('#homeRepos'),l=$('#repoList');h.innerHTML='';l.innerHTML='';state.repos.forEach(r=>{h.appendChild(card(r));l.appendChild(card(r))});$('#homeBlank').style.display=state.repos.length?'none':'block';$('#repoBlank').style.display=state.repos.length?'none':'flex';fillCompare()}
function renderEditor(){const r=repo();if(!r)return;$('#repoName').value=r.name;$('#repoDesc').value=r.description||'';$('#editorName').textContent=r.name;$('#editorHint').textContent=r.description||'Adicione ou altere as informações.';renderRows()}
function renderRows(){const r=repo(),box=$('#editorRows');box.innerHTML='';if(!r)return;r.data.forEach((d,i)=>{const row=document.createElement('div');row.className='data-row';row.innerHTML=`<label>Nome<input class="label" value="${esc(d.label)}"></label><label>Valor<input class="value" type="number" min="0" value="${d.value}"></label><label>Cor<input class="color" type="color" value="${d.color}"></label><button class="remove-row">×</button>`;row.querySelector('.label').oninput=e=>{d.label=e.target.value;save();renderRepos()};row.querySelector('.value').oninput=e=>{d.value=Number(e.target.value)||0;save();renderRepos()};row.querySelector('.color').oninput=e=>{d.color=e.target.value;save();renderRepos();if($('#view-chart').classList.contains('active'))renderChart()};row.querySelector('.remove-row').onclick=()=>{r.data.splice(i,1);save();renderRows();renderRepos()};box.appendChild(row)})}
function createRepo(){const name=$('#newRepoName').value.trim();if(!name){toast('Digite um nome para o repositório.');return}const r={id:id(),name,description:$('#newRepoDesc').value.trim()||'Conjunto de dados do projeto.',data:[{id:id(),label:'Categoria 1',value:0,color:color()}]};state.repos.unshift(r);select(r.id);save();$('#newRepoName').value='';$('#newRepoDesc').value='';close('newRepoModal');renderEditor();renderRepos();go('editor');toast('Repositório criado.')}
function renderLegend(r){const box=$('#customLegend');box.innerHTML='';r.data.forEach((d,i)=>{const b=document.createElement('button');b.className='legend-item '+(state.hidden.has(i)?'off':'');b.innerHTML=`<span class="legend-swatch" style="background:${d.color}"></span>${esc(d.label)}`;b.onclick=()=>{state.hidden.has(i)?state.hidden.delete(i):state.hidden.add(i);renderChart()};box.appendChild(b)})}
function renderChart(){const r=repo();if(!r)return;state.chart?.destroy();const type=state.type==='bar3d'?'bar':state.type;$('#chartShell').classList.toggle('is-3d',state.type==='bar3d');$('#chartName').textContent=r.name;$('#chartDesc').textContent=r.description;$('#chartTotalLabel').textContent=`${r.data.length} ${r.data.length===1?'categoria':'categorias'}`;state.chart=new Chart($('#mainChart'),{type,data:{labels:r.data.map(d=>d.label),datasets:[{data:r.data.map((d,i)=>state.hidden.has(i)?null:d.value),backgroundColor:r.data.map(d=>d.color),borderColor:r.data.map(d=>d.color),borderRadius:type==='bar'?8:0,borderWidth:type==='line'?2:1,pointRadius:type==='line'?5:0}]},options:{responsive:true,maintainAspectRatio:false,animation:{duration:1050,easing:'easeOutQuart',delay:c=>c.dataIndex*90},plugins:{legend:{display:false},tooltip:{backgroundColor:css('--surface'),titleColor:css('--text'),bodyColor:css('--muted'),borderColor:css('--border'),borderWidth:1}},scales:['pie','doughnut','polarArea'].includes(type)?{}:{x:{grid:{display:false},ticks:{color:css('--muted')}},y:{beginAtZero:true,grid:{color:css('--border')},ticks:{color:css('--muted')}}}}});renderLegend(r.data)}
function openChart(){const r=repo();if(!r?.data.length){toast('Adicione pelo menos uma linha de dados.');return}state.hidden.clear();go('chart');renderChart()}
function fillCompare(){const a=$('#compareA'),b=$('#compareB'),av=a.value,bv=b.value;a.innerHTML='<option value="">Selecione...</option>';b.innerHTML='<option value="">Selecione...</option>';state.repos.forEach(r=>{a.add(new Option(r.name,r.id));b.add(new Option(r.name,r.id))});a.value=av;b.value=bv}
function compare(){const a=state.repos.find(r=>r.id===$('#compareA').value),b=state.repos.find(r=>r.id===$('#compareB').value);if(!a||!b)return toast('Escolha os dois repositórios.');if(a.id===b.id)return toast('Escolha dois repositórios diferentes.');const labels=[...new Set([...a.data.map(x=>x.label),...b.data.map(x=>x.label)])];state.compare?.destroy();state.compare=new Chart($('#comparisonChart'),{type:'bar',data:{labels,datasets:[{label:a.name,data:labels.map(l=>a.data.find(x=>x.label===l)?.value||0),backgroundColor:'#5865D9',borderRadius:7},{label:b.name,data:labels.map(l=>b.data.find(x=>x.label===l)?.value||0),backgroundColor:'#2CA878',borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,animation:{duration:1050,easing:'easeOutQuart'},plugins:{legend:{position:'bottom',labels:{usePointStyle:true,color:css('--text')}}},scales:{x:{grid:{display:false}},y:{beginAtZero:true}}}});$('#compareBlank').style.display='none';$('#compareShell').classList.remove('hidden')}
function theme(){const dark=localStorage.getItem('dataview_theme')==='dark';document.body.classList.toggle('dark',dark);$('#themeIcon').textContent=dark?'☀':'☾';$('#themeLabel').textContent=dark?'Modo claro':'Modo escuro'}
function init(){
 $$('.nav-link').forEach(b=>b.onclick=()=>go(b.dataset.route));['headerCreate','heroCreate','repoCreate','repoBlankBtn'].forEach(i=>$('#'+i).onclick=()=>open('newRepoModal'));$('#goRepos').onclick=()=>go('repos');$('#createRepoConfirm').onclick=createRepo;$('#newRepoName').onkeydown=e=>e.key==='Enter'&&createRepo();
 $$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#confirmDelete').onclick=()=>{if(!state.deleteId)return;state.repos=state.repos.filter(r=>r.id!==state.deleteId);if(state.current===state.deleteId)state.current=null;state.deleteId=null;save();close('deleteModal');renderRepos();go('repos');toast('Repositório excluído.')};
 $('#repoName').oninput=e=>{const r=repo();if(!r)return;r.name=e.target.value;$('#editorName').textContent=r.name;save();renderRepos()};$('#repoDesc').oninput=e=>{const r=repo();if(!r)return;r.description=e.target.value;$('#editorHint').textContent=r.description;save();renderRepos()};$('#addRow').onclick=()=>{const r=repo();r.data.push({id:id(),label:`Categoria ${r.data.length+1}`,value:0,color:color()});save();renderRows()};$('#editorBack').onclick=()=>go('repos');$('#openCharts').onclick=openChart;$('#chartBack').onclick=()=>go('editor');$('#chartEdit').onclick=()=>go('editor');
 $$('.type-btn').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;$$('.type-btn').forEach(x=>x.classList.toggle('active',x===b));renderChart()});$('#resetLegend').onclick=()=>{state.hidden.clear();renderChart()};$('#runCompare').onclick=compare;
 $('#themeToggle').onclick=()=>{localStorage.setItem('dataview_theme',document.body.classList.contains('dark')?'light':'dark');theme();if($('#view-chart').classList.contains('active'))renderChart()};
 $('#startWelcome').onclick=()=>{if(step<steps.length-1){step++;tutorial()}else finishTutorial()};$('#skipWelcome').onclick=finishTutorial;$('#openWelcome').onclick=()=>{step=0;tutorial();open('welcome')};$('#headerHelp').onclick=()=>{step=0;tutorial();open('welcome')};$('#heroHow').onclick=()=>{step=0;tutorial();open('welcome')};$('#mobileMenu').onclick=()=>toast('Use o menu lateral para navegar.');
 theme();renderRepos();fillCompare();go('home');tutorial();if(localStorage.getItem('dataview_tutorial_seen'))close('welcome');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();